# Generated by Django 4.2.11 on 2024-04-20 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0002_alter_applicationcontact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontact',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationcontact',
            name='contact_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationcontact',
            name='contact_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
