# Generated by Django 4.2.11 on 2024-04-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_application_document_number_and_more'),
        ('app_contact', '0003_applicationcontact_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontact',
            name='application_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion'),
        ),
        migrations.AlterField(
            model_name='applicationcontact',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
