# Generated by Django 4.2.11 on 2024-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0004_alter_applicationcontact_application_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontact',
            name='contact_type',
            field=models.CharField(choices=[('CELL', 'Cell'), ('EMAIL', 'Email'), ('FAX', 'Fax'), ('LANDLINE', 'Landline'), ('OFFICE_LANDLINE', 'Office Landline')], max_length=100),
        ),
    ]
