# Generated by Django 4.2.11 on 2024-04-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0005_alter_applicationcontact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontact',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
