from .classifier_item_list_view import ClassifierItemListView
from .classifier_item_list_create_view import ClassifierItemListCreateView
from .checklist_classifier_item_modelviewsets import  ChecklistClassifierItemModelViewSets


# Tasks 1 : add modelviewsets for OfficeLocationClassifier
