from .emergency_permit_viewset import EmergencyResidencePermitViewSet
from .exemption_certificate_viewset import ExemptionCertificateViewSet
from .permit_appeal_viewset import PermitAppealViewSet
from .permit_cancellation_viewset import PermitCancellationViewSet
from .work_resident_permit_application_detail_view import (
    WorkResidentPermitApplicationDetailView,
)
from .spouse_create_list_view import SpouseCreateListView
from .child_create_list_view import ChildCreateListView
from .resident_permit_viewset import ResidencePermitViewSet
from .work_resident_permit_application_view import WorkPermitApplicationAPIView
from .work_permit_viewset import WorkPermitViewSet
from .declaration_create_list_view import DeclarationViewSet
from .place_of_residence_viewset import PlaceOfResidenceViewSet

from .production_permit_view import ProductionPermitView

from .travel_certificate_view import TravelCertificateView
from .deferred_application_view import (
    DeferredApplicationView,
    CompleteDeferredApplicationView,
)
from .permit_cancellation_reason_viewset import PermitCancellationReasonViewSet
