# Generated by Django 4.2.11 on 2024-04-13 19:41

import _socket
import base_module.model_fields.hostname_modification_field
import base_module.model_fields.userfield
import base_module.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_applicationuser_alter_applicationdocument_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('iso_code', models.CharField(max_length=2)),
                ('iso_a2_code', models.CharField(max_length=2)),
                ('iso_a3_code', models.CharField(max_length=3)),
                ('cso_code', models.CharField(max_length=3)),
                ('local', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('version', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAddress',
            fields=[
                ('created', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('user_created', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apartment_number', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('address_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('private_bag', models.CharField(max_length=100)),
                ('po_box', models.CharField(max_length=100)),
                ('application_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_address.country')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
