# Generated by Django 4.2.11 on 2024-04-13 19:43

import base_module.model_fields.uuid_auto_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaddress',
            name='id',
            field=base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
