# Generated by Django 4.2.11 on 2024-04-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0003_alter_country_options_country_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationaddress',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
