# Generated by Django 4.2.11 on 2024-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0004_applicationaddress_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
    ]
