from .adopted_child_registration_serializer import AdoptedChildRegistrationSerializer
from .cert_naturalisation_foreign_spouse_serializer import CertNaturalisationByForeignSpouseSerializer
from .citizenship_by_settlement_serializer import CitizenshipBySettlementSerializer
from .citizenship_renunciation_declaration_serializer import CitizenshipRenunciationDeclarationSerializer
from .citizenship_resumption_serializer import CitizenshipResumptionSerializer
from .dc_certificate_serializer import DCCertificateSerializer
from citizenship.api.serializers.declaration_of_intention.decl_naturalisation_foreign_spouse_serializer import DeclNaturalisationForeignSpouseSerializer
from .kgosana_certificate_serializer import KgosanaCertificateSerializer
from .kgosi_certificate_serializer import KgosiCertificateSerializer
from .late_citizenship_renunciation_serializer import LateCitizenshipRenunciationSerializer
from .nationality_declaration_serializer import NationalityDeclarationSerializer
# from .naturalisation_of_foreign_spouse_serializer import NaturalisationOfForeignSpouseSerializer
from .naturalisation_serializer import NaturalisationSerializer
from .oath_of_allegiance_serializer import OathOfAllegianceSerializer
from .parent_details_serializer import ParentDetailsSerializer
from .personal_declaration_serializer import PersonalDeclarationSerializer
from .place_of_residence_serializer import PlaceOfResidenceSerializer
from .renunciation_of_foreign_citizenship_serializer import RenunciationOfForeignCitizenshipSerializer
from .renunciation_of_citizenship_serializer import RenunciationOfCitizenshipSerializer
from .residential_history_serializer import ResidentialHistorySerializer
from .spouse_info_serializer import SpouseInfoSerializer
from .travel_cert_non_citizen_serializer import TravelCertNonCitizenSerializer
from .under_20_citizenship_serializer import Under20CitizenshipSerializer
from .witness_details_serializer import WitnessDetailsSerializer
from .certificate_of_origin_serializer import CertificateOfOriginSerializer
from .citizenship_summary_serializer import CitizenshipSummarySerializer
from .recommendation_decision_serializer import RecommendationDecisionSerializer
from .citizenship_president_decision_serializer import CitizenshipPresidentDecisionSerializer


