from .res_application_view import ResidencePermitDashboardView
from .renewals_view import ResidencePermitRenewalView
from .variation_views import ResidencePermitVariationView
from .cancellation_views import ResidencePermitCancellationView
from .replacement_views import ResidencePermitReplacementView
