from .res_application_view import ResidentPermitDashboardView
from .renewals_view import ResidentPermitRenewalView
from .variation_views import ResidentPermitVariationView
from .cancellation_views import ResidentPermitCancellationView
from .replacement_views import ResidentPermitReplacementView
