from .work_permit_views import WorkPermitDashboardView
from .renewals_view import WorkPermitRenewalView
from .variation_views import WorkPermitVariationView
from .cancellation_views import WorkPermitCancellationView
from .replacement_views import WorkPermitReplacementView
