

class WorkResidentPermitApplicationTypeEnum:

    WORK_PERMIT_ONLY = "WORK_PERMIT_ONLY"
    WORK_PERMIT_EMERGENCY = "WORK_PERMIT_EMERGENCY"
    WORK_PERMIT_EXCEPTION = "WORK_PERMIT_EXCEPTION"
    WORK_PERMIT_CANCELLATION = "WORK_PERMIT_CANCELLATION"
    WORK_PERMIT_REPLACEMENT = "WORK_PERMIT_REPLACEMENT"

    RESIDENT_PERMIT_ONLY = "RESIDENT_PERMIT_ONLY"
    RESIDENT_PERMIT_EMERGENCY = "RESIDENT_PERMIT_EMERGENCY"
    RESIDENT_PERMIT_EXCEPTION = "RESIDENT_PERMIT_EXCEPTION"
    RESIDENT_PERMIT_CANCELLATION = "RESIDENT_PERMIT_CANCELLATION"
    RESIDENT_PERMIT_REPLACEMENT = "RESIDENT_PERMIT_REPLACEMENT"

    WORK_RESIDENT_PERMIT_ONLY = "WORK_RESIDENT_PERMIT_ONLY"
    WORK_RESIDENT_PERMIT_EMERGENCY = "WORK_PERMIT_EMERGENCY"
    WORK_RESIDENT_PERMIT_EXCEPTION = "WORK_PERMIT_EXCEPTION"
    WORK_RESIDENT_PERMIT_CANCELLATION = "WORK_PERMIT_CANCELLATION"
    WORK_RESIDENT_PERMIT_REPLACEMENT = "WORK_PERMIT_REPLACEMENT"
