from .application_recommendation_admin import ApplicationApplicationRecommendationAdmin
from .board_admin import BoardAdmin
from .board_meeting_admin import BoardMeetingAdmin
from .board_member_admin import BoardMemberAdmin
from .interest_declaration_admin import InterestDeclarationAdmin
from .meeting_attendee_admin import MeetingAttendeeAdmin
from .region_admin import RegionAdmin

