# Generated by Django 4.2.11 on 2024-03-30 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_application_version_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('comment', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=100)),
                ('document_date', models.DateField()),
                ('signed_date', models.DateField()),
                ('submission_customer', models.CharField(max_length=250)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='application_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationdocument'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationstatus'),
        ),
    ]
