# Generated by Django 4.2.11 on 2024-03-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_application_options_application_activate_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
