# Generated by Django 4.2.11 on 2024-03-31 22:08

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_application_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='applicationversion',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
