# Generated by Django 4.2.11 on 2024-03-31 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_applicationdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'verbose_name_plural': 'ApplicationDocuments'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name_plural': 'ApplicationStatuses'},
        ),
        migrations.AlterModelOptions(
            name='applicationversion',
            options={'verbose_name_plural': 'ApplicationVersions'},
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
