# Generated by Django 4.2.11 on 2024-04-13 19:51

import _socket
import base_module.model_fields.hostname_modification_field
import base_module.model_fields.userfield
import base_module.model_fields.uuid_auto_field
import base_module.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_applicationuser_alter_applicationdocument_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='application',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='application',
            name='hostname_modified',
            field=base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='user_created',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_modified',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='hostname_modified',
            field=base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='user_created',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='user_modified',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='hostname_modified',
            field=base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='user_created',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='user_modified',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='created',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='hostname_modified',
            field=base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='modified',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='user_created',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='user_modified',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='hostname_modified',
            field=base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='user_created',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='user_modified',
            field=base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='modified',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='created',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='id',
            field=base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='modified',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='created',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='id',
            field=base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='modified',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='id',
            field=base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='created',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='id',
            field=base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='modified',
            field=models.DateTimeField(blank=True, default=base_module.utils.get_utcnow),
        ),
    ]
