# Generated by Django 4.2.11 on 2024-04-15 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='work_location_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
