# Generated by Django 4.2.11 on 2024-04-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_applicationuser_work_location_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationversion',
            old_name='comment',
            new_name='app_comment',
        ),
    ]
