# Generated by Django 4.2.11 on 2024-04-19 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_comment_applicationversion_app_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='dob',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
