# Generated by Django 4.2.11 on 2024-04-19 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_applicationuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
