# Generated by Django 4.2.11 on 2024-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_application_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
    ]
