from .blue_card_application_details import BlueCardApplicationDetails
from .exemption_cert_application_details import ExemptionCertApplicationDetails
from .visa_application_details import VisaApplicationDetails
