from .visa_application_admin import VisaApplicationAdmin
from .blue_card_application_admin import BlueCardApplicationAdmin
from .exemption_cert_application_admin import ExemptionCertificateApplicationAdmin