# Generated by Django 4.2.11 on 2024-04-19 12:01

import _socket
import base_module.model_fields.hostname_modification_field
import base_module.model_fields.userfield
import base_module.model_fields.uuid_auto_field
import base_module.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0011_rename_comment_applicationversion_app_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDecisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('process_types', models.CharField(max_length=250)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDecision',
            fields=[
                ('created', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('user_created', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('id', base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
                ('decision_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_type', to='app_decision.applicationdecisiontype')),
                ('proposed_decision_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_decision_type', to='app_decision.applicationdecisiontype')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
