from .adopted_child_registration import AdoptedChildRegistration
from .cert_naturalisation_by_foreign_spouse import CertNaturalisationByForeignSpouse
from .citizen_sponsor_certificate import CitizenSponsorCertificate
from .citizenship_by_settlement import CitizenshipBySettlement
from .citizenship_renunciation_declaration import CitizenshipRenunciationDeclaration
from .citizenship_resumption import CitizenshipResumption
from .DC_certificate import DCCertificate
from .declaration_naturalisation_by_foreign_spouse import (
    DeclarationNaturalisationByForeignSpouse,
)
from .doubt_citizenship_certificate import DoubtCitizenshipCertificate
from .kgosi_certificate import KgosiCertificate
from .kgosana_certificate import KgosanaCertificate
from .late_citizenship_renunciation import LateCitizenshipRenunciation
from .maturity_period_waiver import MaturityPeriodWaiver
from .nationality_declaration import NationalityDeclaration
from .naturalisation import Naturalisation
from .oath_of_allegiance import OathOfAllegiance
from citizenship.models.renunciation.renunciation_of_citizenship import (
    RenunciationOfCitizenship,
)
from .renunciation_of_foreign_citizenship import RenunciationOfForeignCitizenship
from .parent_details import ParentDetails
from .personal_declaration import PersonalDeclaration
from .place_of_residence import PlaceOfResidence
from .president_power_10A import PresidentPower10A
from .president_power_10B import PresidentPower10B
from .residential_history import ResidentialHistory
from .spouse_info import SpouseInfo
from .travel_certificate_non_citizen import TravelCertNonCitizen
from .under_20_citizenship import Under20Citizenship
from .witness_details import WitnessDetails
from .board.attendee import Attendee
from .board.board_member import BoardMember
from .board.role import Role
from .board.meeting_session import MeetingSession
from .board.score_sheet import ScoreSheet
from .board.score_sheet_detail import ScoreSheetDetail
from .board.interview import Interview
from .board.interview_question import InterviewQuestion
from .board.interview_response import InterviewResponse
from .board.meeting import Meeting
from .board.interview_decision import InterviewDecision
from .board.conflict_of_interest import ConflictOfInterest
from .board.board_recommandation import BoardRecommendation
from .board.batch import Batch
from .board.batch_application import BatchApplication
from .board.board import Board
from .board.question import Question
from .board.conflict_of_interest_duration import ConflictOfInterestDuration
from .citizenship_summary import CitizenshipSummary
