from .child_serializer import ChildSerializer
from .emergency_residence_permit_serializer import EmergencyResidencePermitSerializer
from .emergency_res_permit_application_serializer import EmergencyResPermitApplicationSerializer
from .exemption_certificate_serializer import ExemptionCertificateSerializer
from .permit_serializer import PermitSerializer
from .residence_permit_appeal_serializer import ResidencePermitAppealSerializer
from .residence_permit_cancellation_serializer import ResidencePermitCancellationSerializer
from .spouse_serializer import SpouseSerializer
from .work_residence_permit_serializer import WorkResidencePermitSerializer
from .work_res_permit_data_serializer import WorkResidentPermitDataSerializer
from .place_of_residence_serializer import PlaceOfResidenceSerializer, SpousePlaceOfResidenceSerializer
