from .emergency_permit_serializer import EmergencyPermitSerializer
from .exemption_certificate_serializer import ExemptionCertificateSerializer
from .permit_appeal_serializer import PermitAppealSerializer
from .permit_cancellation_serializer import PermitCancellationSerializer
from .residence_permit_serializer import ResidencePermitSerializer
from .work_res_permit_data_serializer import WorkResidentPermitDataSerializer
from .place_of_residence_serializer import (
    PlaceOfResidenceSerializer,
    SpousePlaceOfResidenceSerializer,
)
from .declaration_serializer import DeclarationSerializer
from .work_permit_serializer import WorkPermitSerializer

from .permit_replacement_serializer import PermitReplacementSerializer

from .request_deferred_application_dto import RequestDeferredApplicationDTOSerializer
from .permit_cancellation_reason_serializer import PermitCancellationReasonSerializer
