# Generated by Django 4.2.11 on 2024-04-15 18:32

import _socket
import base_module.model_fields.hostname_modification_field
import base_module.model_fields.userfield
import base_module.model_fields.uuid_auto_field
import base_module.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_applicationuser_work_location_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('user_created', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('id', base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=190)),
                ('last_name', models.CharField(max_length=190)),
                ('middle_name', models.CharField(blank=True, max_length=190, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=190, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced')], max_length=50)),
                ('dob', models.DateField()),
                ('country_birth', models.CharField(max_length=190)),
                ('place_birth', models.CharField(max_length=190)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('occupation', models.CharField(max_length=190)),
                ('qualification', models.CharField(max_length=190)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
            ],
            options={
                'verbose_name': 'Personal Details',
                'verbose_name_plural': 'Personal Details',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('created', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('user_created', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('id', base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('permit_type', models.CharField(max_length=190)),
                ('permit_no', models.CharField(max_length=190)),
                ('date_issued', models.DateField()),
                ('date_expiry', models.DateField()),
                ('place_issue', models.CharField(max_length=190)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
            ],
            options={
                'verbose_name': 'Permit',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('created', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('user_created', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('id', base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=15, verbose_name='Passport number')),
                ('date_issued', models.DateField(verbose_name='Date of issue')),
                ('place_issued', models.CharField(max_length=190, verbose_name='Country of issue')),
                ('expiry_date', models.DateField(verbose_name='Date of expiry')),
                ('nationality', models.CharField(max_length=190)),
                ('photo', models.URLField()),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
            ],
            options={
                'verbose_name': 'Passport',
            },
        ),
    ]
