# Generated by Django 4.2.11 on 2024-04-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_application_application_type'),
        ('app_personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='application_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion', unique=True),
        ),
    ]
