# Generated by Django 4.2.11 on 2024-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personal_details', '0002_alter_person_application_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
    ]
