# Generated by Django 4.2.11 on 2024-04-19 11:51

import _socket
import base_module.model_fields.hostname_modification_field
import base_module.model_fields.userfield
import base_module.model_fields.uuid_auto_field
import base_module.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_rename_comment_applicationversion_app_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=base_module.utils.get_utcnow)),
                ('user_created', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', base_module.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', base_module.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('id', base_module.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_type', models.CharField(max_length=50)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
