# Generated by Django 4.2.11 on 2024-04-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_applicationuser_alter_applicationdocument_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentDocumentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('storage_object_key', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=400)),
                ('document_url', models.CharField(max_length=150)),
                ('received_date', models.DateTimeField()),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicationversion')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_attachments.attachmentdocumenttype')),
            ],
        ),
    ]
