from enum import Enum


class CitizenshipApplicationTypeEnum(Enum):

    RENUNCIATION_ONLY = "RENUNCIATION_ONLY"
    UNDER_20_CITIZENSHIP_ONLY = "CITIZENSHIP_FOR_UNDER_20_ONLY"
    ADOPTED_CHILD_REGISTRATION_ONLY = "REGISTRATION_OF_ADOPTED_CHILD_OVER_3YEARS_ONLY"
    INTENTION_FOREIGN_SPOUSE_ONLY = "NATURALIZATION_INTENTION_FOREIGN_SPOUSE_ONLY"
    MATURITY_PERIOD_WAIVER_ONLY = "MATURITY_PERIOD_WAIVER_ONLY"
    PRESIDENT_POWER_10B_ONLY = "PRESIDENT_POWER_REGISTER_CITIZENS_10B_ONLY"

