from enum import Enum


class CitizenshipStagesEnum(Enum):

    VERIFICATION = "VERIFICATION"
    FIRST_ASSESSMENT = "FIRST_ASSESSMENT"
    SECOND_ASSESSMENT = "SECOND_ASSESSMENT"
    THIRD_ASSESSMENT = "THIRD_ASSESSMENT"
    MINISTER_ACCEPTANCE = "MINISTER_ACCEPTANCE"
    FOREIGN_RENUNCIATION = "FOREIGN_RENUNCIATION"
