from enum import Enum


class CitizenshipStagesEnum(Enum):

    VERIFICATION = "VERIFICATION"
    ASSESSMENT = "ASSESSMENT"
    REVIEW = "REVIEW"
    VETTING = "VETTING"
    RECOMMENDATION = "RECOMMENDATION"
    MINISTER_DECISION = "MINISTER_DECISION"
    MINISTER_ACCEPTANCE = "MINISTER_ACCEPTANCE"
    FOREIGN_RENUNCIATION = "FOREIGN_RENUNCIATION"
