frame = """
<html>
<head>
<style>
    @page {
        size: letter portrait;
        @frame header_frame {           /* Static frame */
            -pdf-frame-content: header_content;
            left: 50pt; width: 512pt; top: 50pt; height: 200pt;
        }
        
        @frame content_frame {
            left: 50pt;
            width: 512pt;
            top: 200pt;
            height: 500pt;
            -pdf-frame-border: 1; 
        }
        
        @frame footer_frame {           /* Static frame */
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 20pt;
        }
    }
    
    .container {
    text-align: left; /* Center content horizontally */
    }
    
    .container img {
        display: inline-block; /* Make image a block element */
        max-width: 100%; /* Ensure image doesn't exceed container width */
        height: auto; /* Maintain aspect ratio */
    }

</style>
<head>
<body>

    <div id="header_content">
        <div class="container">
            <img src="{{ image_url }}" alt="Logo" width="100%" height="100%">
        </div>
    </div>
    
     <p>
     {{ data }} 
     </p>
    <p>
     {{ data }} 
     </p>
     
    <p>
     {{ data }} 
     </p>
    <div id="footer_content">
        Page <pdf:pagenumber>
        of <pdf:pagecount>                                Generated By easyPermits System.

    </div>
    
</body>
</html>

"""