from .child import Child
from .emergency_residence_permit import EmergencyResidencePermit
from .emergency_res_permit_application import EmergencyResPermitApplication
from .exemption_certificate import ExemptionCertificate
from .residence_permit_appeal import ResidencePermitAppeal
from .residence_permit_cancellation import ResidencePermitCancellation
from .spouse import Spouse
from .permit import Permit
from .work_resident_permit import WorkResidencePermit
from .place_of_residence import PlaceOfResidence, SpousePlaceOfResidence
from .declaration import Declaration
