# Generated by Django 4.2.11 on 2024-04-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifieritem',
            old_name='related_model',
            new_name='classifier',
        ),
    ]
