# Generated by Django 4.2.11 on 2024-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_checklist', '0004_alter_classifier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classifieritem',
            name='document_number',
            field=models.CharField(blank=True, help_text='Application number', max_length=255, null=True),
        ),
    ]
